[10/10/2024]
[BACKEND]
Implemeted these API
1: HseSafetyChecklistHV [create, update, get, update, aproved, delete]
2: HseSafetyTT [create, update, get, update, aproved, delete]
3: HseSafetyBT [create, update, get, update, aproved, delete]
4: HseSafetyCTCVTPT [create, update, get, update, aproved, delete]
5: HseSafetyHandling [create, update, get, update, aproved, delete]
6: HseSafetyRelay [create, update, get, update, aproved, delete]
7: HseSafetySwitchgear [create, update, get, update, aproved, delete]